field: 989f6b5c-82cf-4a15-aa85-fe9b821cee4b
fieldLayouts:
  9784d67b-9217-4a82-8f71-1492976e4790:
    tabs:
      -
        elements:
          -
            fieldUid: d569c65b-2978-43ee-bbe9-724c8b6823d8
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d569c65b-2978-43ee-bbe9-724c8b6823d8:
    contentColumnType: string
    fieldGroup: null
    handle: externalVideo
    instructions: 'Upload a video from YouTube or Vimeo.'
    name: 'External video'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - json
        - video
      defaultUploadLocationSource: 'volume:81307dab-347a-4fb8-b528-45b18ed7d0e0'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Embed a video'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:81307dab-347a-4fb8-b528-45b18ed7d0e0'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:81307dab-347a-4fb8-b528-45b18ed7d0e0'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: externalVideo
name: 'External video'
sortOrder: 7
