field: 37791995-fc9d-4977-9057-ad800dd1b735
fieldLayouts:
  77357e29-d8f9-4383-b3b2-ead5fe80866d:
    tabs:
      -
        elements:
          -
            fieldUid: 6d85fef4-37dc-4f7f-9262-4313c67f0860
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b2d3a28-340a-4a61-b2e5-f55aea8a2595
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d85fef4-37dc-4f7f-9262-4313c67f0860:
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: 'Select the page to list in the menu.'
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:3a95c5ae-691b-45a9-af63-804ec4f32d8f'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7b2d3a28-340a-4a61-b2e5-f55aea8a2595:
    contentColumnType: text
    fieldGroup: null
    handle: rename
    instructions: 'If the menu item requires a custom title.'
    name: Rename
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: menuItem
name: 'Menu item'
sortOrder: 1
