fieldLayouts:
  cccf2e51-0c4a-4de8-a32f-42e8bdea8239:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 879df627-dfbf-4b0f-ac8c-45a8808db488
            warning: null
            width: 100
          -
            fieldUid: 1b332dd3-a72e-41bc-af7f-2cb86bd9e378 # Page Components
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bccbf0f-aab9-4e59-9b22-768f59b0ba40
            warning: null
            width: 100
        name: Content
        uid: 9d5e893f-4a63-4567-86f6-d0f6e5c060e2
handle: homepage
hasTitleField: true
name: Homepage
section: 7295f06d-67a8-4ad1-91aa-df78d4ceb502 # Site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
