fieldLayouts:
  7a219a51-c790-425d-bc44-b45644449f70:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 39f8cfcf-152c-4306-b6ed-6d6493366cde
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d16e6c1e-b44e-4cf8-aae2-6fa250b73706
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 39a3b015-426d-4a46-9c15-8676081b5a00
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: testimonial
hasTitleField: false
name: Testimonial
section: a69bd831-e1ab-4132-84fd-d36a262b6a46
sortOrder: 1
titleFormat: '{{ quote|length > 50 ? quote|striptags|slice(0, 50) ~ ''...'' : quote|striptags }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
