handle: footerUtilityMenu
instructions: 'This is the small menu in the footer for utility links such as ''terms and conditions''.'
maxNodes: ''
name: 'Footer Utility Menu'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  734c8496-7eca-4f66-8377-dba7854a48eb: null # JayCraft
sortOrder: 2
structure:
  maxLevels: '1'
  uid: 25203337-c91d-40a9-8aab-7e8d3bb31b5a
