handle: mainNavigation
instructions: 'This is the main navigation menu at the top of the site. For the best user experience, have no more than seven at the top level.'
maxNodes: ''
name: 'Main Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  734c8496-7eca-4f66-8377-dba7854a48eb: null # JayCraft
sortOrder: 1
structure:
  maxLevels: null
  uid: 8d7fcb71-2cd9-49dd-834e-ff4f38ed5aa6
