fieldLayouts:
  887e33da-703c-497e-b41b-9e0d5c698243:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 0136bb82-6130-48c6-88cc-015d69da6199
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: image
hasUrls: true
name: Image
settings:
  path: '@webroot/uploads/image'
sortOrder: 3
type: craft\volumes\Local
url: $ASSET_BASE_URL/image
