contentColumnType: string
fieldGroup: be866704-e9e5-489a-94b0-c7763eec7317
handle: pageComponents
instructions: 'Build your page with these elements.'
name: 'Page components'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagecomponents}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
