contentColumnType: text
fieldGroup: be866704-e9e5-489a-94b0-c7763eec7317
handle: role
instructions: 'What is their position to make their testimonial relevant?'
name: Role
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
