columnSuffix: fmzquufs
contentColumnType: text
fieldGroup: be866704-e9e5-489a-94b0-c7763eec7317
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  editCanonical: false
  enableMetaDetailsFields: false
  optimizedDescriptionField: manually
  optimizedImageField: ''
  optimizedKeywordsField: manually
  optimizedTitleField: elementTitle
  schemaOverrideTypeId: ''
  schemaTypeId: ''
  showGeo: ''
  showOpenGraph: ''
  showRobots: ''
  showSearchMeta: ''
  showTwitter: ''
translationKeyFormat: null
translationMethod: none
type: barrelstrength\sproutseo\fields\ElementMetadata
