columnSuffix: null
contentColumnType: string
fieldGroup: b4265419-d2d6-4b1c-b601-52a06c58c2f8 # Globals
handle: socialNetworks
instructions: ''
name: 'Social Networks'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''verbb\supertable\fields\SuperTableField''.'
  expectedType: verbb\supertable\fields\SuperTableField
  settings: '{"columns":{"69634719-284a-4131-97f3-c1765dbb0a7f":{"width":""},"deb21e5d-868e-403f-a997-68474902a793":{"width":""}},"contentTable":"{{%stc_socialnetworks}}","fieldLayout":"row","maxRows":"","minRows":"","placeholderKey":null,"propagationKeyFormat":null,"propagationMethod":"all","selectionLabel":"","staticField":""}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
