contentColumnType: string
fieldGroup: 9d0976d6-6ff8-4790-9e75-5bb37d331d19
handle: socialAccounts
instructions: 'Add social media accounts'
name: 'Social accounts'
searchable: false
settings:
  contentTable: '{{%matrixcontent_socialaccounts}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
