contentColumnType: text
fieldGroup: 9d0976d6-6ff8-4790-9e75-5bb37d331d19
handle: tags
instructions: 'Hashtags included in any Twitter, Facebook or LinkedIn share features.'
name: Tags
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
