field: 1c3609c8-6750-4ecd-8f5b-da0b920d40ea # Social Networks
fieldLayouts:
  b1791de0-6eff-4be5-8272-0a4aa80e92f3:
    tabs:
      -
        elements:
          -
            fieldUid: ec6081a9-87b4-42ae-b261-6fdd2d496956 # Network
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b9d2e78-50a2-4344-89fe-16f091143755 # Account Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6b9d2e78-50a2-4344-89fe-16f091143755: # Account Url
    columnSuffix: yefrdgxi
    contentColumnType: string(255)
    fieldGroup: null
    handle: accountUrl
    instructions: 'Paste the full network url.'
    name: 'Account Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  ec6081a9-87b4-42ae-b261-6fdd2d496956: # Network
    columnSuffix: sfvypyqo
    contentColumnType: string
    fieldGroup: null
    handle: network
    instructions: ''
    name: Network
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - facebook
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twitter
            -
              - value
              - twitter
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - instagram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - YouTube
            -
              - value
              - youtube
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - LinkedIn
            -
              - value
              - linkedin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Spotify
            -
              - value
              - spotify
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Pinterest
            -
              - value
              - pinterest
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - SoundCloud
            -
              - value
              - soundcloud
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Vimeo
            -
              - value
              - vimeo
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - ''
            -
              - value
              - ''
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
