currLabel: 'Sprout SEO'
customIcon: null
enabled: true
handle: sprout-seo
icon: /Users/jaycollett/Sites/jaystack/jaycraft/vendor/barrelstrength/sprout-seo/src/icon-mask.svg
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: false
order: 9999
prevLabel: 'Sprout SEO'
prevUrl: sprout-seo
type: ''
url: sprout-seo
