currLabel: 'Unsplash Images'
customIcon: ''
enabled: true
handle: splashing-images
icon: /app/vendor/studioespresso/craft-splashingimages/src/icon-mask.svg
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 9
prevLabel: 'Unsplash Images'
prevUrl: splashing-images
type: ''
url: splashing-images
