currLabel: Assets
customIcon: null
enabled: '1'
handle: assets
icon: assets
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: '0'
order: 3
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
