currLabel: Uploads
customIcon: ''
enabled: true
handle: assets
icon: ''
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 8
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
