currLabel: Config
customIcon: null
enabled: '1'
handle: divider
icon: null
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: false
order: '7'
prevLabel: Divider
prevUrl: null
type: divider
url: null
