currLabel: Globals
customIcon: ''
enabled: true
handle: globals
icon: globe
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 4
prevLabel: Globals
prevUrl: globals
type: ''
url: globals
