currLabel: Navigation
customIcon: null
enabled: '1'
handle: navigation
icon: menu
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: false
order: '6'
prevLabel: Navigation
prevUrl: navigation
type: ''
url: navigation
