currLabel: Navigation
customIcon: ''
enabled: true
handle: navigation
icon: /app/vendor/verbb/navigation/src/icon-mask.svg
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 5
prevLabel: Navigation
prevUrl: navigation
type: ''
url: navigation
