currLabel: Settings
customIcon: ''
enabled: true
handle: settings
icon: settings
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 11
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
