currLabel: Settings
customIcon: null
enabled: '1'
handle: settings
icon: settings
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: '0'
order: 8
prevLabel: Settings
prevUrl: settings
type: '0'
url: settings
