currLabel: Users
customIcon: null
enabled: true
handle: users
icon: users
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: false
order: 9999
prevLabel: Users
prevUrl: users
type: ''
url: users
