currLabel: Utilities
customIcon: ''
enabled: true
handle: utilities
icon: tool
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 12
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
