enableVersioning: true
handle: news
name: News
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  f1e03893-0fd0-4d36-87b3-4269d461b769:
    enabledByDefault: true
    hasUrls: true
    template: /pages
    uriFormat: 'news/{slug}'
type: channel
